In [2]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('data/2021AcordosBilaterais.txt', sep = ';')
df

,NacionalidadeEmbarcacao,Ano Acordo Bilateral,Total Acordo Bilateral,AcordoTipoNavegacao,País,FlagEmbarqueDesembarque
0,Brasilieiras,2021,"2020555,6129999",Longo Curso,ARGENTINA,1
1,Estrangeiras,2021,"9523483,2190007",Longo Curso,ARGENTINA,1
2,Estrangeiras,2021,"9439,786",Longo Curso,BULGÁRIA,1
3,Brasilieiras,2021,"262,917",Longo Curso,BULGÁRIA,1
4,Estrangeiras,2021,"2917456,794",Longo Curso,CHILE,1
5,Brasilieiras,2021,"237476,42",Longo Curso,CHILE,1
6,Estrangeiras,2021,"19824324,918001",Longo Curso,CHINA,1
7,Brasilieiras,2021,"391480,682",Longo Curso,CHINA,1
8,Estrangeiras,2021,"2538220,661",Longo Curso,ALEMANHA,1
9,Brasilieiras,2021,"121020,777",Longo Curso,ALEMANHA,1
10,Estrangeiras,2021,"2626160,82",Longo Curso,ARGÉLIA,1
11,Brasilieiras,2021,"1987,1",Longo Curso,ARGÉLIA,1
12,Estrangeiras,2021,"580263,187",Longo Curso,FRANÇA,1
13,Brasilieiras,2021,"15649,125",Longo Curso,FRANÇA,1
14,Estrangeiras,2021,"323423,252",Longo Curso,POLÔNIA,1
15,Brasilieiras,2021,"11460,885",Longo Curso,POLÔNIA,1
16,Estrangeiras,2021,"486929,06299999",Longo Curso,PORTUGAL,1
17,Brasilieiras,2021,"15891,403",Longo Curso,PORTUGAL,1
18,Brasilieiras,2021,"2297,897",Longo Curso,ROMÊNIA,1
19,Estrangeiras,2021,"93901,69",Longo Curso,ROMÊNIA,1
20,Estrangeiras,2021,"13290807,698",Longo Curso,RUSSIA,1
21,Brasilieiras,2021,"142312,248",Longo Curso,RUSSIA,1
22,Estrangeiras,2021,"37463234,259006",Longo Curso,ESTADOS UNIDOS,1
23,Brasilieiras,2021,"5672109,564",Longo Curso,ESTADOS UNIDOS,1
24,Estrangeiras,2021,"1258934,7599999",Longo Curso,URUGUAI,1
25,Brasilieiras,2021,"158153,353",Longo Curso,URUGUAI,1
26,Estrangeiras,2021,"6197509,613",Longo Curso,ARGENTINA,2
27,Brasilieiras,2021,"1463820,389",Longo Curso,ARGENTINA,2
28,Estrangeiras,2021,"2399902,663",Interior,ARGENTINA,2
29,Estrangeiras,2021,"216473,333",Longo Curso,BULGÁRIA,2
30,Brasilieiras,2021,"336581,007",Longo Curso,CHILE,2
31,Estrangeiras,2021,"3581437,252",Longo Curso,CHILE,2
32,Estrangeiras,2021,"343273107,65904",Longo Curso,CHINA,2
33,Brasilieiras,2021,"1459787,798",Longo Curso,CHINA,2
34,Estrangeiras,2021,"4128137,637",Longo Curso,ALEMANHA,2
35,Brasilieiras,2021,"92653,797",Longo Curso,ALEMANHA,2
36,Estrangeiras,2021,"4224958,216",Longo Curso,ARGÉLIA,2
37,Estrangeiras,2021,"5987186,823",Longo Curso,FRANÇA,2
38,Brasilieiras,2021,"20765,074",Longo Curso,FRANÇA,2
39,Brasilieiras,2021,"3417,798",Longo Curso,POLÔNIA,2
40,Estrangeiras,2021,"745510,328",Longo Curso,POLÔNIA,2
41,Estrangeiras,2021,"4027212,158",Longo Curso,PORTUGAL,2
42,Brasilieiras,2021,"814042,748",Longo Curso,PORTUGAL,2
43,Estrangeiras,2021,"1000414,805",Longo Curso,ROMÊNIA,2
44,Estrangeiras,2021,"1556522,942",Longo Curso,RUSSIA,2
45,Brasilieiras,2021,"3751,544",Longo Curso,RUSSIA,2
46,Estrangeiras,2021,"28269543,701",Longo Curso,ESTADOS UNIDOS,2
47,Brasilieiras,2021,"724580,838",Longo Curso,ESTADOS UNIDOS,2
48,Estrangeiras,2021,"567687,111",Longo Curso,URUGUAI,2
49,Brasilieiras,2021,"98152,279",Longo Curso,URUGUAI,2
50,Estrangeiras,2021,734757,Interior,URUGUAI,2

In [8]:
df = pd.read_csv('data/2021Atracacao.txt', sep = ';')
df

,IDAtracacao,CDTUP,IDBerco,Berço,Porto Atracação,Apelido Instalação Portuária,Complexo Portuário,Tipo da Autoridade Portuária,Data Atracação,Data Chegada,...,Tipo de Navegação da Atracação,Nacionalidade do Armador,FlagMCOperacaoAtracacao,Terminal,Município,UF,SGUF,Região Geográfica,Nº da Capitania,Nº do IMO
0,1200419,BRSTM,STM0502,SAN0502,Santarém,NaN,Santarém,Porto Público,15/11/2021 08:02:00,15/11/2021 08:00:00,...,Interior,1.0,1,Cais Público,Santarém,Pará,PA,Norte,NaN,NaN
1,1206357,BRSTM,STM0502,SAN0502,Santarém,NaN,Santarém,Porto Público,01/12/2021 14:07:00,01/12/2021 14:05:00,...,Interior,1.0,1,Cais Público,Santarém,Pará,PA,Norte,NaN,NaN
2,3298,BR,NaN,NaN,NaN,NaN,Não Classificado,Porto Público,NaN,NaN,...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1187610,BRSTM,STM0502,SAN0502,Santarém,NaN,Santarém,Porto Público,03/09/2021 17:52:00,03/09/2021 17:50:00,...,Interior,1.0,1,Cais Público,Santarém,Pará,PA,Norte,NaN,NaN
4,1158910,BRBEL,BEL0001,01,Belém,NaN,Vila do Conde - Belém,Porto Público,26/05/2021 20:15:00,26/05/2021 20:15:00,...,Cabotagem,1.0,1,Cais Público,Belém,Pará,PA,Norte,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77742,1215450,BRAM069,BRAM0695001,Berço 1 - Rampa móvel,Ponta Negra,NaN,Manaus,Porto Privado,20/12/2021 08:00:00,20/12/2021 07:00:00,...,Interior,1.0,1,Ponta Negra,Manaus,Amazonas,AM,Norte,0010193260,NaN
77743,1215458,BRAM069,BRAM0695001,Berço 1 - Rampa móvel,Ponta Negra,NaN,Manaus,Porto Privado,29/12/2021 08:00:00,29/12/2021 07:00:00,...,Interior,1.0,1,Ponta Negra,Manaus,Amazonas,AM,Norte,0010153446,NaN
77744,1215477,BRPA043,BRPA0435001,Píer de Navios,Terminal Vila do Conde,Hidrovias do Brasil Vila do Conde,Vila do Conde - Belém,Porto Privado,22/12/2021 10:36:00,17/12/2021 10:36:00,...,Longo Curso,2.0,1,Terminal Vila do Conde,Barcarena,Pará,PA,Norte,NaN,9757008.0
77745,1215493,BRPA043,BRPA0435001,Píer de Navios,Terminal Vila do Conde,Hidrovias do Brasil Vila do Conde,Vila do Conde - Belém,Porto Privado,25/12/2021 12:54:00,22/12/2021 01:24:00,...,Longo Curso,2.0,1,Terminal Vila do Conde,Barcarena,Pará,PA,Norte,NaN,9579054.0
77746,1215539,BRPA043,BRPA0435001,Píer de Navios,Terminal Vila do Conde,Hidrovias do Brasil Vila do Conde,Vila do Conde - Belém,Porto Privado,09/12/2021 12:25:00,06/12/2021 07:50:00,...,Longo Curso,2.0,1,Terminal Vila do Conde,Barcarena,Pará,PA,Norte,NaN,9650171.0

In [9]:
df = pd.read_csv('data/2021Carga.txt', sep = ';')
df

/tmp/ipykernel_9954/3972226587.py:1: DtypeWarning: Columns (12,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/2021Carga.txt', sep = ';')

,IDCarga,IDAtracacao,Origem,Destino,CDMercadoria,Tipo Operação da Carga,Carga Geral Acondicionamento,ConteinerEstado,Tipo Navegação,FlagAutorizacao,...,Percurso Transporte em vias Interiores,Percurso Transporte Interiores,STNaturezaCarga,STSH2,STSH4,Natureza da Carga,Sentido,TEU,QTCarga,VLPesoCargaBruta
0,27502716,1126626,BR200,BRBEL,2710,Interior,NaN,NaN,Interior,S,...,Interior de percurso não identificado,Navegação Interior,Exclusivo,Exclusivo,Exclusivo,Granel Líquido e Gasoso,Desembarcados,0,0,"2476,46"
1,27502733,1126639,BRBEL,BRMCP,2710,Interior,NaN,NaN,Interior,S,...,NaN,NaN,Exclusivo,Compartilhado,Compartilhado,Granel Líquido e Gasoso,Embarcados,0,0,"264,5"
2,27502734,1126639,BRBEL,BRMCP,2207,Interior,NaN,NaN,Interior,S,...,NaN,NaN,Exclusivo,Compartilhado,Compartilhado,Granel Líquido e Gasoso,Embarcados,0,0,"890,66"
3,27502737,1126643,USHOU,BRBEL,2710,Longo Curso Importação,NaN,NaN,Longo Curso,S,...,NaN,Longo Curso em vias interiores,Exclusivo,Exclusivo,Exclusivo,Granel Líquido e Gasoso,Desembarcados,0,0,"4551,95"
4,27502738,1126643,USHOU,BRBEL,2710,Longo Curso Importação,NaN,NaN,Longo Curso,S,...,NaN,Longo Curso em vias interiores,Exclusivo,Exclusivo,Exclusivo,Granel Líquido e Gasoso,Desembarcados,0,0,"834,73"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2350075,3333,3333,BRISA,BR289,2505,NaN,NaN,NaN,Interior,N,...,Interior Estadual,Navegação Interior,Compartilhado,Compartilhado,Compartilhado,Granel Sólido,Desembarcados,0,0,2400
2350076,3334,3334,BRISA,BR289,2505,NaN,NaN,NaN,Interior,N,...,Interior Estadual,Navegação Interior,Compartilhado,Compartilhado,Compartilhado,Granel Sólido,Desembarcados,0,0,2400
2350077,3335,3335,BR368,BR372,2505,NaN,NaN,NaN,Interior,N,...,Interior Estadual,Navegação Interior,Compartilhado,Compartilhado,Compartilhado,Granel Sólido,Desembarcados,0,0,11750
2350078,3336,3336,BR368,BR372,2505,NaN,NaN,NaN,Interior,N,...,Interior Estadual,Navegação Interior,Compartilhado,Compartilhado,Compartilhado,Granel Sólido,Desembarcados,0,0,9500
2350079,3337,3337,BR365,BR369,1212,NaN,NaN,NaN,Interior,N,...,Interior Estadual,Navegação Interior,Compartilhado,Compartilhado,Compartilhado,Granel Sólido,Desembarcados,0,0,26322

In [10]:
df = pd.read_csv('data/2021Carga_Conteinerizada.txt', sep = ';')
df

/tmp/ipykernel_9954/2328187549.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/2021Carga_Conteinerizada.txt', sep = ';')

          IDCarga CDMercadoriaConteinerizada VLPesoCargaConteinerizada
0        27673235                       0101                      4,22
1        27697257                       0101                      4,99
2        27697277                       0101                      5,71
3        27697280                       0101                      1,84
4        27748701                       0101                      23,3
...           ...                        ...                       ...
4211517  30197852                       R9P0                         0
4211518  30545592                       R9P0                         0
4211519  30607145                       R9P0                         0
4211520  30606505                       R9P0                         0
4211521  30606506                       R9P0                         0

[4211522 rows x 3 columns]

In [11]:
df = pd.read_csv('data/2021Carga_Regiao.txt', sep = ';')
df

         IDCarga            Região Hidrográfica ValorMovimentado
0       27502716                            NaN         2476,460
1       27502737                            NaN         4551,950
2       27502738                            NaN          834,730
3       27502739                            NaN          417,370
4       27502740                            NaN         3937,240
...          ...                            ...              ...
536722      3333  Região Hidrográfica do Paraná         2400,000
536723      3334  Região Hidrográfica do Paraná         2400,000
536724      3335  Região Hidrográfica do Paraná        11750,000
536725      3336  Região Hidrográfica do Paraná         9500,000
536726      3337  Região Hidrográfica do Paraná            26322

[536727 rows x 3 columns]

In [12]:
df = pd.read_csv('data/2021TemposAtracacao.txt', sep = ';')
df

,IDAtracacao,TEsperaAtracacao,TEsperaInicioOp,TOperacao,TEsperaDesatracacao,TAtracado,TEstadia
0,1169791,"15,29999999993","5,4166666666861","88,583333333256","2,25","96,249999999942","111,54999999987"
1,1169990,"104,86666666676","6,2999999999302","20,100000000035","19,899999999907","46,299999999872","151,16666666663"
2,1169992,"0,48333333333721","0,18333333340706","26,749999999884","0,23333333339542","27,166666666686","27,650000000023"
3,1170005,"0,48333333333721","0,18333333323244","64,250000000058","0,23333333339542","64,666666666686","65,150000000023"
4,1170006,"0,48333333333721","0,18333333323244","1,1666666668025","0,2333333332208","1,5833333332557","2,0666666665929"
...,...,...,...,...,...,...,...
75046,1205640,"0,016666666720994",0,0,0,"37,983333333337","38,000000000058"
75047,1205639,"0,016666666720994",0,0,0,"61,983333333337","62,000000000058"
75048,1205651,"0,016666666720994",0,0,0,"61,983333333337","62,000000000058"
75049,1205650,"0,016666666720994",0,0,0,"37,983333333337","38,000000000058"
75050,1205645,"0,016666666720994",0,0,0,"61,983333333337","62,000000000058"